# Generated by Django 4.2.5 on 2023-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
